threecctofourcc={
    "BUF":"RBUF",
    "CNT":"PCNT",
    "COM":"COMM",
    "CRA":"AENC",
    "CRM":None, #Obsolete and dropped(?)
    "ETC":"ETCO",
    "EQU":"EQUA",
    "GEO":"GEOB",
    "IPL":"IPLS",
    "LNK":"LINK"
    #...
    'TAL': 'TALB',
    'TBP': 'TBPM',
    'TCM': 'TCOM',
    'TCO': 'TCON',
    'TCR': 'TCOP',
    'TDA': 'TDAT',
    'TDY': 'TDLY',
    'TEN': 'TENC',
    'TFT': 'TFLT',
    'TIM': 'TIME',
    'TKE': 'TKEY',
    'TLA': 'TLAN',
    'TLE': 'TLEN',
    'TMT': 'TMED',
    'TOA': 'TOPE',
    'TOF': 'TOFN',
    'TOL': 'TOLY',
    'TOR': 'TORY',
    'TOT': 'TOAL',
    'TP1': 'TPE1',
    'TP2': 'TPE2',
    'TP3': 'TPE3',
    'TP4': 'TPE4',
    'TPA': 'TPOS',
    'TPB': 'TPUB',
    'TRC': 'TSRC',
    'TRD': 'TRDA',
    'TRK': 'TRCK',
    'TSI': 'TSIZ',
    'TSS': 'TSSE',
    'TT1': 'TIT1',
    'TT2': 'TIT2',
    'TT3': 'TIT3',
    'TXT': 'TEXT',
    'TXX': 'TXXX',
    'TYE': 'TYER',
    #...
}